#
# CSE183 Assignment 9 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 9 Backend
  version: 0.1.0
  title: CSE183 Assignment 9 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  # /dummy:
  #   get:
  #     description: Dummy Endpoint
  #     responses:
  #       200:
  #         description: Succesful
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/DummyResponse'
  #       default:
  #         description: unexpected error
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  /mail/all/count:
    get:
      description: "Get list of all mailboxes and the number of emails in them"
      responses:
        200:
          description: "All good"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mailbox"

components:
  schemas:
    Mailbox:
      properties:
        name:
          type: string
        size:
          type: number
          format: int32
        mail:
          type: array
          items:
            $ref: "#/components/schemas/Email"
    User:
      properties:
        id:
          type: string
          format: uuid
        avatar:
          type: string
          format: uri
        name:
          type: string
        email:
          type: string
          format: email
    Email:
      properties:
        to:
          $ref: '#/components/schemas/User'
        from:
          $ref: '#/components/schemas/User'
        subject:
          type: string
        content: 
          type: string
        sent:
          type: string
          format: date-time
        received:
          type: string
          format: date-time




    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    DummyResponse:
      required:
        - message
      properties:
        message:
          type: string